setwd("#~//...To wherever the file is put")
p11 <- read.csv(file=".../TDP-43 Required files for replication/Files/...",sep=",",head=T)
p12 <- read.csv(file=".../TDP-43 Required files for replication/Files/...",sep=",",head=T)
p13 <- read.csv(file=".../TDP-43 Required files for replication/Files/...",sep=",",head=T)
p21 <- read.csv(file=".../TDP-43 Required files for replication/Files/...",sep=",",head=T)
p22 <- read.csv(file=".../TDP-43 Required files for replication/Files/...",sep=",",head=T)
p23 <- read.csv(file=".../TDP-43 Required files for replication/Files/...",sep=",",head=T)
p31 <- read.csv(file=".../TDP-43 Required files for replication/Files/...",sep=",",head=T)
p32 <- read.csv(file=".../TDP-43 Required files for replication/Files/...",sep=",",head=T)
p33 <- read.csv(file=".../TDP-43 Required files for replication/Files/...",sep=",",head=T)